In [118]:
import tensorflow as tf

In [119]:
data=tf.data.Dataset.range(10)
for i in data:
    print(i.numpy())

0
1
2
3
4
5
6
7
8
9


In [120]:
dataset=data.window(size=6,shift=1)
for w_data in dataset:
    print(w_data)

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


In [121]:
len(dataset)

10

In [122]:
for w_data in dataset:
    a=[]
    for i in w_data:
        a.append(i.numpy())
    print(a)

[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6, 7]
[3, 4, 5, 6, 7, 8]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [123]:
for w_data in dataset:
    print([i.numpy() for i in w_data])

[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6, 7]
[3, 4, 5, 6, 7, 8]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [124]:
dataset=data.window(size=5,shift=1,drop_remainder=True) 
dataset=dataset.flat_map(lambda window: window.batch(5))
for i in dataset:
    print(i.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [125]:
dataset=dataset.map(lambda window: (window[:-1],window[-1]))
for i,j in dataset:
    print('X: ',i.numpy())
    print('Y: ',j.numpy())

X:  [0 1 2 3]
Y:  4
X:  [1 2 3 4]
Y:  5
X:  [2 3 4 5]
Y:  6
X:  [3 4 5 6]
Y:  7
X:  [4 5 6 7]
Y:  8
X:  [5 6 7 8]
Y:  9


In [126]:
dataset=dataset.shuffle(buffer_size=10)
for i,j in dataset:
    print(i.numpy())
    print(j.numpy())


[2 3 4 5]
6
[5 6 7 8]
9
[3 4 5 6]
7
[0 1 2 3]
4
[1 2 3 4]
5
[4 5 6 7]
8


In [127]:
dataset=dataset.batch(2).prefetch(1)
for i,j in dataset:
    print(i.numpy())
    print(j.numpy())

[[1 2 3 4]
 [3 4 5 6]]
[5 7]
[[2 3 4 5]
 [0 1 2 3]]
[6 4]
[[4 5 6 7]
 [5 6 7 8]]
[8 9]
